### ISSUE TITLE
Enhancement: Edit the generated commit message

### ISSUE THREAD

**Issue by stowu2005** [edwardyeung04/commitment-issues#10]
Currently, when you select edit after generating a commit message, it lets you write a brand new commit message using a template. While this is fine, I think it would be better to have an option to edit the generated commit message itself (without having to start over), since some small changes do not warrant a complete re-write of the message.

**Comment by fishbearr** [comment]
Thank you for this suggestion. Unfortunately implementing this functionality is outside the scope of our project. Instead we have updated our user-facing documentation to suggest an alternative; users can simply copy/paste the original version of the generated message as a starting point and make their edits from there.

**Comment by fishbearr** [comment]
actually, just wanted to add that another way to accomplish these small edits is to use the regenerate feature.
