### ISSUE TITLE
Enhancement: Have option to go back a prompt

### ISSUE THREAD

**Issue by stowu2005** [edwardyeung04/commitment-issues#11]
Right now, there is no obvious option to go back a prompt (inputting an invalid change type does go back a prompt, but it is not in the documentation), which could be useful if you mistype something and go to the next prompt so you don't have to re-make the commit message.

**Comment by fishbearr** [comment]
This is a great suggestion. Unfortunately this is out of scope for our project in this course. The best workaround is to regenerate the message after all the prompts have completed.
