### ISSUE TITLE
Bug: Throws Error when generating complex commit message

### ISSUE THREAD

**Issue by stowu2005** [edwardyeung04/commitment-issues#12]
When running python cli.py commit -m c, it prints out: 

"Generated commit message contains unexpected extra sections.
Response from GPT:
 chore | frontend: Remove unused test file from CLI interface

            **Git Diff Changes:**
            ```
            diff --git a/cli_interface/test b/cli_interface/test
deleted file mode 100644
index e69de29..0000000
            ```
The unused test file in the CLI interface has been removed to clean up the project and reduce unnecessary clutter. This helps maintain a more manageable codebase by eliminating files that are no longer needed.
Error: Failed to generate commit message."

It throws an error at the end about failing to generate a commit message despite generating what seems like a commit message, and stops the program immediately. There also seems to be unnecessary text at the top ("Response from GPT:").

Running python cli.py commit works without issue.

"Generated commit message:
chore | cli_interface: Remove unused test file"

I have tried running this with multiple different commits, and am having the same bug.

**Comment by fishbearr** [comment]
Thank you for pointing out this issue with our response processor. It has been resolved!
