### ISSUE TITLE
Continuous Integration Pylint tests failing

### ISSUE THREAD

**Issue by anmolkb** [edwardyeung04/commitment-issues#15]
![image](https://github.com/user-attachments/assets/86b32b01-fb52-47f0-9fda-4231b71a8422)

The Continuous Integration setup is clear and it appears to be functioning correctly, but it seems that the Pylint tests are currently failing, so that might be worth looking into.

**Comment by fishbearr** [comment]
Being resolved, thanks for bringing this up
