### ISSUE TITLE
Bug Documentation

### ISSUE THREAD

**Issue by Revenantsghost** [edwardyeung04/commitment-issues#16]
Firstly, I love the fact your team is documenting bugs. However, I would consider not just keeping your logs potentially more up-to-date (I notice the last update to the bug file was 2weeks ago) but also perhaps provide more detail. By only documenting where a bug exists and not what the problem is (e.g. expected output vs actual output) it might make it more difficult to go back later and rectify your bugs.

**Comment by fishbearr** [comment]
thank you for the suggestion! right now we have a very casual way of reporting bugs for simplicity but in theory more detail would be preferred
