### ISSUE TITLE
Potential "touch .env" dependency

### ISSUE THREAD

**Issue by Frangkris** [edwardyeung04/commitment-issues#7]
I have git, and python updated and installed. I'm running on a windows machine.

It seems that the touch command is not immediately recognized. 
![Screenshot 2024-11-19 135613](https://github.com/user-attachments/assets/1fb34cc1-204a-4c60-9fb7-d53ae00cf824)

A fix I found is writing this in the terminal

"npm install touch-cli -g"

It may be something to consider for your guys' README.md

**Comment by anmolkb** [comment]
I'm also running on a windows machine and the command `touch .env` is giving me the same error.

**Comment by fishbearr** [comment]
Thank you for pointing out this confusion. This detail has been removed. The file can be created with any method compatible with your machine, not just via the touch command.
