### ISSUE TITLE
High-Level Suggestion: Ability to change commit message format

### ISSUE THREAD

**Issue by Revenantsghost** [edwardyeung04/commitment-issues#8]
Currently, it seems like you only support one particular commit message format. Although you offer the option to edit the commit message, it would be a cool extension to be able to edit the actual format itself in addition to being able to edit specific messages. I think the base format is great, but certain groups may need additional customizability to support their project.

**Comment by fishbearr** [comment]
Thanks for the wonderful suggestion! Unfortunately that is outside the scope of the project in this course, but is a reasonable feature to add in the future should this product be used.
