### ISSUE TITLE
Lack of clarity on Developer/User manual

### ISSUE THREAD

**Issue by Frangkris** [edwardyeung04/commitment-issues#9]
In the assignment last week, there was a point to make clear user and developer manuals. While we can see how to use your code, there is not a designated space specifically for just users, it seems that you guys group the two into one documentation.

![Screenshot 2024-11-19 141010](https://github.com/user-attachments/assets/0777954d-c4c2-48c0-82ea-0523c89a4091)

**Comment by fishbearr** [comment]
Seems like there was a misunderstanding here. Our README.md file acts as the user-facing manual and the DEV_GUIDE.md acts as the developer-facing manual. Sorry that the former was not named clearly!
